# Generated by Django 5.1.1 on 2024-09-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testmodel_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='MyModel',
        ),
    ]
